### ISSUE TITLE
Incorrect skip message

### ISSUE THREAD

**Issue by eserte** [clustericious/Test-Clustericious-Blocking#2]
The skip message in https://metacpan.org/source/PLICEASE/Test-Clustericious-Blocking-0.02/t/cluster.t#L16 lists a wrong module name: it says "Test::Clustericious 0.25", but it should be "Test::Clustericious::Cluster 0.25".

**Comment by plicease** [comment]
ah I wish I had waited to push out 0.03.  This will be fixed in the next version if there is one.
